### ISSUE TITLE
不外接显示器，内建显示屏是否正常使用呢？

### ISSUE THREAD

**Issue by vaakian** [cc336625/Hasee-k670d_Hackintosh#3]
先谢谢兄弟，机型配置跟我一模一样，刚换的qn8h。

**Comment by carrot0219** [comment]
解决了吗  开机后再插入hdmi就可以了

**Comment by vaakian** [comment]
> 解决了吗 开机后再插入hdmi就可以了

谢谢没问题了，但是我刷的D大bios没找到cfg lock，用不了openCore，用的兄弟你之前的Clover版本。
可以麻烦告知下cfg lock设置的选项在哪个菜单吗？谢谢啦~
